server:
  port: 8084

spring:
  application:
    name: shopping-cart-service
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}

credit:
  card:
    authorizer:
      url: ${CREDIT_CARD_AUTHORIZER_URL:http://localhost:8082/credit-card-authorizer/authorize}

product:
  service:
    url: ${PRODUCT_SERVICE_URL:http://localhost:8083}

warehouse:
  service:
    url: ${WAREHOUSE_SERVICE_URL:http://localhost:8081}