server:
  port: 8081

spring:
  application:
    name: shopping-cart-service
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:guest}
    password: ${RABBITMQ_PASS:guest}

credit:
  card:
    authorizer:
      url: ${CCA_URL:http://localhost:8082/credit-card-authorizer/authorize}