spring.application.name=shopping-cart-service
server.port=8084
database.url=${DATABASE_URL:http://localhost:9080}
credit.card.authorizer.url=${CREDIT_CARD_AUTHORIZER_URL:http://localhost:8082/credit-card-authorizer/authorize}